### ISSUE TITLE
test time optimization

### ISSUE THREAD

**Issue by lzl2040** [qianqianwang68/omnimotion#2]
Why is it a test-time optimization method? I do not find something is adopted in the test stage.

**Comment by rlee3359** [comment]
For each video, they optimize the model on all frames that can then be queried to track pixels through the video. Thus it is a "test-time" optimization method since there is no set of weights or something that works on all videos, you instead build the representation of the whole video and then you can do tracking. It's like a NeRF that requires a bunch of frames to make the implicit representation.

**Comment by qianqianwang68** [comment]
@rlee3359 's explanation is correct. Thank you! Let me know if there is any other question.
